INSERT INTO caloric_items (item_name, calorie_count, calories_per_day, protein_amount) VALUES ('Apple', 52, 2000, 0);
INSERT INTO caloric_items (item_name, calorie_count, calories_per_day, protein_amount) VALUES ('Banana', 89, 2000, 1);
INSERT INTO caloric_items (item_name, calorie_count, calories_per_day, protein_amount) VALUES ('Orange', 47, 2000, 1);
INSERT INTO caloric_items (item_name, calorie_count, calories_per_day, protein_amount) VALUES ('Grapes', 69, 2000, 1);
INSERT INTO caloric_items (item_name, calorie_count, calories_per_day, protein_amount) VALUES ('Watermelon', 30, 2000, 1);
INSERT INTO caloric_items (item_name, calorie_count, calories_per_day, protein_amount) VALUES ('Mango', 60, 2000, 1);
INSERT INTO caloric_items (item_name, calorie_count, calories_per_day, protein_amount) VALUES ('Strawberry', 33, 2000, 1);
INSERT INTO caloric_items (item_name, calorie_count, calories_per_day, protein_amount) VALUES ('Pineapple', 50, 2000, 1);
INSERT INTO caloric_items (item_name, calorie_count, calories_per_day, protein_amount) VALUES ('Papaya', 43, 2000, 0);
INSERT INTO caloric_items (item_name, calorie_count, calories_per_day, protein_amount) VALUES ('Avocado', 160, 2000, 2);
INSERT INTO caloric_items (item_name, calorie_count, calories_per_day, protein_amount) VALUES ('Tomato', 18, 2000, 1);
INSERT INTO caloric_items (item_name, calorie_count, calories_per_day, protein_amount) VALUES ('Potato', 77, 2000, 2);
INSERT INTO caloric_items (item_name, calorie_count, calories_per_day, protein_amount) VALUES ('Carrot', 41, 2000, 1);
INSERT INTO caloric_items (item_name, calorie_count, calories_per_day, protein_amount) VALUES ('Broccoli', 34, 2000, 3);
INSERT INTO caloric_items (item_name, calorie_count, calories_per_day, protein_amount) VALUES ('Cucumber', 16, 2000, 1);
INSERT INTO caloric_items (item_name, calorie_count, calories_per_day, protein_amount) VALUES ('Spinach', 23, 2000, 3);
INSERT INTO caloric_items (item_name, calorie_count, calories_per_day, protein_amount) VALUES ('Onion', 40, 2000, 1);
INSERT INTO caloric_items (item_name, calorie_count, calories_per_day, protein_amount) VALUES ('Garlic', 149, 2000, 6);
INSERT INTO caloric_items (item_name, calorie_count, calories_per_day, protein_amount) VALUES ('Peas', 81, 2000, 5);
INSERT INTO caloric_items (item_name, calorie_count, calories_per_day, protein_amount) VALUES ('Corn', 86, 2000, 3);
INSERT INTO caloric_items (item_name, calorie_count, calories_per_day, protein_amount) VALUES ('Rice', 130, 2000, 3);
INSERT INTO caloric_items (item_name, calorie_count, calories_per_day, protein_amount) VALUES ('Pasta', 131, 2000, 5);
INSERT INTO caloric_items (item_name, calorie_count, calories_per_day, protein_amount) VALUES ('Bread', 265, 2000, 9);
INSERT INTO caloric_items (item_name, calorie_count, calories_per_day, protein_amount) VALUES ('Oatmeal', 68, 2000, 2);
INSERT INTO caloric_items (item_name, calorie_count, calories_per_day, protein_amount) VALUES ('Egg', 155, 2000, 13);
INSERT INTO caloric_items (item_name, calorie_count, calories_per_day, protein_amount) VALUES ('Chicken Breast', 165, 2000, 31);
INSERT INTO caloric_items (item_name, calorie_count, calories_per_day, protein_amount) VALUES ('Beef', 250, 2000, 26);
INSERT INTO caloric_items (item_name, calorie_count, calories_per_day, protein_amount) VALUES ('Pork', 242, 2000, 27);
INSERT INTO caloric_items (item_name, calorie_count, calories_per_day, protein_amount) VALUES ('Lamb', 294, 2000, 25);
INSERT INTO caloric_items (item_name, calorie_count, calories_per_day, protein_amount) VALUES ('Fish (Salmon)', 208, 2000, 20);
INSERT INTO caloric_items (item_name, calorie_count, calories_per_day, protein_amount) VALUES ('Shrimp', 99, 2000, 24);
INSERT INTO caloric_items (item_name, calorie_count, calories_per_day, protein_amount) VALUES ('Tuna', 132, 2000, 28);
INSERT INTO caloric_items (item_name, calorie_count, calories_per_day, protein_amount) VALUES ('Milk', 42, 2000, 3);
INSERT INTO caloric_items (item_name, calorie_count, calories_per_day, protein_amount) VALUES ('Cheese', 402, 2000, 25);
INSERT INTO caloric_items (item_name, calorie_count, calories_per_day, protein_amount) VALUES ('Butter', 717, 2000, 1);
INSERT INTO caloric_items (item_name, calorie_count, calories_per_day, protein_amount) VALUES ('Yogurt', 59, 2000, 10);
INSERT INTO caloric_items (item_name, calorie_count, calories_per_day, protein_amount) VALUES ('Ice Cream', 207, 2000, 4);
INSERT INTO caloric_items (item_name, calorie_count, calories_per_day, protein_amount) VALUES ('Chocolate', 546, 2000, 5);
INSERT INTO caloric_items (item_name, calorie_count, calories_per_day, protein_amount) VALUES ('Coffee', 2, 2000, 0);
INSERT INTO caloric_items (item_name, calorie_count, calories_per_day, protein_amount) VALUES ('Tea', 1, 2000, 0);
INSERT INTO caloric_items (item_name, calorie_count, calories_per_day, protein_amount) VALUES ('Sugar', 387, 2000, 0);
INSERT INTO caloric_items (item_name, calorie_count, calories_per_day, protein_amount) VALUES ('Honey', 304, 2000, 0);
INSERT INTO caloric_items (item_name, calorie_count, calories_per_day, protein_amount) VALUES ('Olive Oil', 884, 2000, 0);
INSERT INTO caloric_items (item_name, calorie_count, calories_per_day, protein_amount) VALUES ('Coconut Oil', 862, 2000, 0);
INSERT INTO caloric_items (item_name, calorie_count, calories_per_day, protein_amount) VALUES ('Peanut Butter', 588, 2000, 25);
INSERT INTO caloric_items (item_name, calorie_count, calories_per_day, protein_amount) VALUES ('Almonds', 579, 2000, 21);
INSERT INTO caloric_items (item_name, calorie_count, calories_per_day, protein_amount) VALUES ('Walnuts', 654, 2000, 15);
INSERT INTO caloric_items (item_name, calorie_count, calories_per_day, protein_amount) VALUES ('Cashews', 553, 2000, 18);
INSERT INTO caloric_items (item_name, calorie_count, calories_per_day, protein_amount) VALUES ('Peanuts', 567, 2000, 26);
INSERT INTO caloric_items (item_name, calorie_count, calories_per_day, protein_amount) VALUES ('Sunflower Seeds', 584, 2000, 21);
INSERT INTO caloric_items (item_name, calorie_count, calories_per_day, protein_amount) VALUES ('Pumpkin Seeds', 559, 2000, 30);
INSERT INTO caloric_items (item_name, calorie_count, calories_per_day, protein_amount) VALUES ('Lentils', 116, 2000, 9);
INSERT INTO caloric_items (item_name, calorie_count, calories_per_day, protein_amount) VALUES ('Chickpeas', 164, 2000, 9);
INSERT INTO caloric_items (item_name, calorie_count, calories_per_day, protein_amount) VALUES ('Kidney Beans', 127, 2000, 9);
INSERT INTO caloric_items (item_name, calorie_count, calories_per_day, protein_amount) VALUES ('Tofu', 76, 2000, 8);
INSERT INTO caloric_items (item_name, calorie_count, calories_per_day, protein_amount) VALUES ('Soybeans', 446, 2000, 36);
INSERT INTO caloric_items (item_name, calorie_count, calories_per_day, protein_amount) VALUES ('Tempeh', 193, 2000, 19);
INSERT INTO caloric_items (item_name, calorie_count, calories_per_day, protein_amount) VALUES ('Quinoa', 120, 2000, 4);
INSERT INTO caloric_items (item_name, calorie_count, calories_per_day, protein_amount) VALUES ('Couscous', 112, 2000, 4);
INSERT INTO caloric_items (item_name, calorie_count, calories_per_day, protein_amount) VALUES ('Barley', 354, 2000, 12);
INSERT INTO caloric_items (item_name, calorie_count, calories_per_day, protein_amount) VALUES ('Buckwheat', 343, 2000, 13);
INSERT INTO caloric_items (item_name, calorie_count, calories_per_day, protein_amount) VALUES ('Rye', 335, 2000, 10);
INSERT INTO caloric_items (item_name, calorie_count, calories_per_day, protein_amount) VALUES ('Oats', 389, 2000, 17);
INSERT INTO caloric_items (item_name, calorie_count, calories_per_day, protein_amount) VALUES ('Wheat Flour', 364, 2000, 10);
INSERT INTO caloric_items (item_name, calorie_count, calories_per_day, protein_amount) VALUES ('Pancakes', 227, 2000, 6);
INSERT INTO caloric_items (item_name, calorie_count, calories_per_day, protein_amount) VALUES ('Waffles', 291, 2000, 7);
INSERT INTO caloric_items (item_name, calorie_count, calories_per_day, protein_amount) VALUES ('Croissant', 406, 2000, 8);
INSERT INTO caloric_items (item_name, calorie_count, calories_per_day, protein_amount) VALUES ('Bagel', 250, 2000, 10);
INSERT INTO caloric_items (item_name, calorie_count, calories_per_day, protein_amount) VALUES ('Burger Patty', 295, 2000, 19);
INSERT INTO caloric_items (item_name, calorie_count, calories_per_day, protein_amount) VALUES ('Hotdog', 290, 2000, 10);
INSERT INTO caloric_items (item_name, calorie_count, calories_per_day, protein_amount) VALUES ('Pizza', 266, 2000, 11);
INSERT INTO caloric_items (item_name, calorie_count, calories_per_day, protein_amount) VALUES ('French Fries', 312, 2000, 4);
INSERT INTO caloric_items (item_name, calorie_count, calories_per_day, protein_amount) VALUES ('Popcorn', 387, 2000, 12);
INSERT INTO caloric_items (item_name, calorie_count, calories_per_day, protein_amount) VALUES ('Chips', 536, 2000, 7);
INSERT INTO caloric_items (item_name, calorie_count, calories_per_day, protein_amount) VALUES ('Noodles', 138, 2000, 5);
INSERT INTO caloric_items (item_name, calorie_count, calories_per_day, protein_amount) VALUES ('Ramen', 380, 2000, 10);
INSERT INTO caloric_items (item_name, calorie_count, calories_per_day, protein_amount) VALUES ('Dumplings', 229, 2000, 8);
INSERT INTO caloric_items (item_name, calorie_count, calories_per_day, protein_amount) VALUES ('Spring Roll', 154, 2000, 4);
INSERT INTO caloric_items (item_name, calorie_count, calories_per_day, protein_amount) VALUES ('Sushi', 130, 2000, 6);
INSERT INTO caloric_items (item_name, calorie_count, calories_per_day, protein_amount) VALUES ('Cereal', 379, 2000, 8);
INSERT INTO caloric_items (item_name, calorie_count, calories_per_day, protein_amount) VALUES ('Granola', 471, 2000, 13);
INSERT INTO caloric_items (item_name, calorie_count, calories_per_day, protein_amount) VALUES ('Porridge', 71, 2000, 2);
INSERT INTO caloric_items (item_name, calorie_count, calories_per_day, protein_amount) VALUES ('Soup (Tomato)', 40, 2000, 2);
INSERT INTO caloric_items (item_name, calorie_count, calories_per_day, protein_amount) VALUES ('Soup (Chicken)', 75, 2000, 6);
INSERT INTO caloric_items (item_name, calorie_count, calories_per_day, protein_amount) VALUES ('Soup (Vegetable)', 45, 2000, 2);
INSERT INTO caloric_items (item_name, calorie_count, calories_per_day, protein_amount) VALUES ('Salad (Mixed)', 33, 2000, 2);
INSERT INTO caloric_items (item_name, calorie_count, calories_per_day, protein_amount) VALUES ('Caesar Salad', 190, 2000, 8);
INSERT INTO caloric_items (item_name, calorie_count, calories_per_day, protein_amount) VALUES ('Taco', 226, 2000, 10);
INSERT INTO caloric_items (item_name, calorie_count, calories_per_day, protein_amount) VALUES ('Burrito', 206, 2000, 10);
INSERT INTO caloric_items (item_name, calorie_count, calories_per_day, protein_amount) VALUES ('Enchilada', 168, 2000, 8);
INSERT INTO caloric_items (item_name, calorie_count, calories_per_day, protein_amount) VALUES ('Fajita', 201, 2000, 14);
INSERT INTO caloric_items (item_name, calorie_count, calories_per_day, protein_amount) VALUES ('Lasagna', 135, 2000, 7);
INSERT INTO caloric_items (item_name, calorie_count, calories_per_day, protein_amount) VALUES ('Spaghetti', 158, 2000, 6);
INSERT INTO caloric_items (item_name, calorie_count, calories_per_day, protein_amount) VALUES ('Meatballs', 257, 2000, 18);
INSERT INTO caloric_items (item_name, calorie_count, calories_per_day, protein_amount) VALUES ('Steak', 271, 2000, 25);
INSERT INTO caloric_items (item_name, calorie_count, calories_per_day, protein_amount) VALUES ('Roast Beef', 217, 2000, 26);
INSERT INTO caloric_items (item_name, calorie_count, calories_per_day, protein_amount) VALUES ('Ham', 145, 2000, 20);
INSERT INTO caloric_items (item_name, calorie_count, calories_per_day, protein_amount) VALUES ('Bacon', 541, 2000, 37);
INSERT INTO caloric_items (item_name, calorie_count, calories_per_day, protein_amount) VALUES ('Sausage', 301, 2000, 12);
INSERT INTO caloric_items (item_name, calorie_count, calories_per_day, protein_amount) VALUES ('Turkey', 189, 2000, 29);
INSERT INTO caloric_items (item_name, calorie_count, calories_per_day, protein_amount) VALUES ('Duck', 337, 2000, 19);
INSERT INTO caloric_items (item_name, calorie_count, calories_per_day, protein_amount) VALUES ('Goose', 305, 2000, 25);
INSERT INTO caloric_items (item_name, calorie_count, calories_per_day, protein_amount) VALUES ('Crab', 97, 2000, 20);
INSERT INTO caloric_items (item_name, calorie_count, calories_per_day, protein_amount) VALUES ('Lobster', 89, 2000, 19);
INSERT INTO caloric_items (item_name, calorie_count, calories_per_day, protein_amount) VALUES ('Clams', 74, 2000, 13);
INSERT INTO caloric_items (item_name, calorie_count, calories_per_day, protein_amount) VALUES ('Oysters', 68, 2000, 7);
INSERT INTO caloric_items (item_name, calorie_count, calories_per_day, protein_amount) VALUES ('Mussels', 86, 2000, 12);
INSERT INTO caloric_items (item_name, calorie_count, calories_per_day, protein_amount) VALUES ('Scallops', 111, 2000, 20);
INSERT INTO caloric_items (item_name, calorie_count, calories_per_day, protein_amount) VALUES ('Prawns', 99, 2000, 24);
INSERT INTO caloric_items (item_name, calorie_count, calories_per_day, protein_amount) VALUES ('Octopus', 164, 2000, 30);
INSERT INTO caloric_items (item_name, calorie_count, calories_per_day, protein_amount) VALUES ('Squid', 92, 2000, 16);
INSERT INTO caloric_items (item_name, calorie_count, calories_per_day, protein_amount) VALUES ('Calamari', 175, 2000, 15);
INSERT INTO caloric_items (item_name, calorie_count, calories_per_day, protein_amount) VALUES ('Anchovies', 210, 2000, 29);
INSERT INTO caloric_items (item_name, calorie_count, calories_per_day, protein_amount) VALUES ('Mackerel', 205, 2000, 19);
INSERT INTO caloric_items (item_name, calorie_count, calories_per_day, protein_amount) VALUES ('Trout', 141, 2000, 20);
INSERT INTO caloric_items (item_name, calorie_count, calories_per_day, protein_amount) VALUES ('Sardines', 208, 2000, 25);
INSERT INTO caloric_items (item_name, calorie_count, calories_per_day, protein_amount) VALUES ('Herring', 158, 2000, 18);
INSERT INTO caloric_items (item_name, calorie_count, calories_per_day, protein_amount) VALUES ('Catfish', 105, 2000, 18);
INSERT INTO caloric_items (item_name, calorie_count, calories_per_day, protein_amount) VALUES ('Cod', 82, 2000, 18);
INSERT INTO caloric_items (item_name, calorie_count, calories_per_day, protein_amount) VALUES ('Haddock', 90, 2000, 20);
INSERT INTO caloric_items (item_name, calorie_count, calories_per_day, protein_amount) VALUES ('Halibut', 140, 2000, 27);
INSERT INTO caloric_items (item_name, calorie_count, calories_per_day, protein_amount) VALUES ('Tilapia', 129, 2000, 26);
INSERT INTO caloric_items (item_name, calorie_count, calories_per_day, protein_amount) VALUES ('Snapper', 100, 2000, 20);
INSERT INTO caloric_items (item_name, calorie_count, calories_per_day, protein_amount) VALUES ('Eggplant', 25, 2000, 1);
INSERT INTO caloric_items (item_name, calorie_count, calories_per_day, protein_amount) VALUES ('Zucchini', 17, 2000, 1);
INSERT INTO caloric_items (item_name, calorie_count, calories_per_day, protein_amount) VALUES ('Bell Pepper', 31, 2000, 1);
INSERT INTO caloric_items (item_name, calorie_count, calories_per_day, protein_amount) VALUES ('Chili Pepper', 40, 2000, 2);
INSERT INTO caloric_items (item_name, calorie_count, calories_per_day, protein_amount) VALUES ('Cabbage', 25, 2000, 1);
INSERT INTO caloric_items (item_name, calorie_count, calories_per_day, protein_amount) VALUES ('Cauliflower', 25, 2000, 2);
INSERT INTO caloric_items (item_name, calorie_count, calories_per_day, protein_amount) VALUES ('Kale', 49, 2000, 4);
INSERT INTO caloric_items (item_name, calorie_count, calories_per_day, protein_amount) VALUES ('Lettuce', 15, 2000, 1);
INSERT INTO caloric_items (item_name, calorie_count, calories_per_day, protein_amount) VALUES ('Mushroom', 22, 2000, 3);
INSERT INTO caloric_items (item_name, calorie_count, calories_per_day, protein_amount) VALUES ('Celery', 16, 2000, 1);
INSERT INTO caloric_items (item_name, calorie_count, calories_per_day, protein_amount) VALUES ('Radish', 16, 2000, 1);
INSERT INTO caloric_items (item_name, calorie_count, calories_per_day, protein_amount) VALUES ('Beetroot', 43, 2000, 2);
INSERT INTO caloric_items (item_name, calorie_count, calories_per_day, protein_amount) VALUES ('Turnip', 28, 2000, 1);
INSERT INTO caloric_items (item_name, calorie_count, calories_per_day, protein_amount) VALUES ('Sweet Potato', 86, 2000, 2);
INSERT INTO caloric_items (item_name, calorie_count, calories_per_day, protein_amount) VALUES ('Pumpkin', 26, 2000, 1);
INSERT INTO caloric_items (item_name, calorie_count, calories_per_day, protein_amount) VALUES ('Apple Pie', 237, 2000, 2);
INSERT INTO caloric_items (item_name, calorie_count, calories_per_day, protein_amount) VALUES ('Donut', 452, 2000, 5);
INSERT INTO caloric_items (item_name, calorie_count, calories_per_day, protein_amount) VALUES ('Cupcake', 305, 2000, 4);
INSERT INTO caloric_items (item_name, calorie_count, calories_per_day, protein_amount) VALUES ('Muffin', 377, 2000, 6);
INSERT INTO caloric_items (item_name, calorie_count, calories_per_day, protein_amount) VALUES ('Brownie', 405, 2000, 5);
INSERT INTO caloric_items (item_name, calorie_count, calories_per_day, protein_amount) VALUES ('Pancake Syrup', 260, 2000, 0);
INSERT INTO caloric_items (item_name, calorie_count, calories_per_day, protein_amount) VALUES ('Jam', 278, 2000, 0);
INSERT INTO caloric_items (item_name, calorie_count, calories_per_day, protein_amount) VALUES ('Ketchup', 112, 2000, 1);
INSERT INTO caloric_items (item_name, calorie_count, calories_per_day, protein_amount) VALUES ('Mayonnaise', 680, 2000, 1);
INSERT INTO caloric_items (item_name, calorie_count, calories_per_day, protein_amount) VALUES ('Mustard', 66, 2000, 4);
INSERT INTO caloric_items (item_name, calorie_count, calories_per_day, protein_amount) VALUES ('Vinegar', 21, 2000, 0);
INSERT INTO caloric_items (item_name, calorie_count, calories_per_day, protein_amount) VALUES ('Soy Sauce', 53, 2000, 5);
INSERT INTO caloric_items (item_name, calorie_count, calories_per_day, protein_amount) VALUES ('BBQ Sauce', 175, 2000, 1);
INSERT INTO caloric_items (item_name, calorie_count, calories_per_day, protein_amount) VALUES ('Hot Sauce', 12, 2000, 1);
INSERT INTO caloric_items (item_name, calorie_count, calories_per_day, protein_amount) VALUES ('Salad Dressing', 430, 2000, 1);
INSERT INTO caloric_items (item_name, calorie_count, calories_per_day, protein_amount) VALUES ('Ice Tea', 30, 2000, 0);
INSERT INTO caloric_items (item_name, calorie_count, calories_per_day, protein_amount) VALUES ('Lemonade', 40, 2000, 0);
INSERT INTO caloric_items (item_name, calorie_count, calories_per_day, protein_amount) VALUES ('Coke', 42, 2000, 0);
INSERT INTO caloric_items (item_name, calorie_count, calories_per_day, protein_amount) VALUES ('Sprite', 41, 2000, 0);
INSERT INTO caloric_items (item_name, calorie_count, calories_per_day, protein_amount) VALUES ('Orange Juice', 45, 2000, 1);
INSERT INTO caloric_items (item_name, calorie_count, calories_per_day, protein_amount) VALUES ('Apple Juice', 46, 2000, 0);
INSERT INTO caloric_items (item_name, calorie_count, calories_per_day, protein_amount) VALUES ('Grape Juice', 60, 2000, 1);
INSERT INTO caloric_items (item_name, calorie_count, calories_per_day, protein_amount) VALUES ('Milkshake', 112, 2000, 4);
INSERT INTO caloric_items (item_name, calorie_count, calories_per_day, protein_amount) VALUES ('Smoothie', 50, 2000, 2);
INSERT INTO caloric_items (item_name, calorie_count, calories_per_day, protein_amount) VALUES ('Beer', 43, 2000, 0);
INSERT INTO caloric_items (item_name, calorie_count, calories_per_day, protein_amount) VALUES ('Wine', 85, 2000, 0);
INSERT INTO caloric_items (item_name, calorie_count, calories_per_day, protein_amount) VALUES ('Whiskey', 250, 2000, 0);
INSERT INTO caloric_items (item_name, calorie_count, calories_per_day, protein_amount) VALUES ('Vodka', 231, 2000, 0);
INSERT INTO caloric_items (item_name, calorie_count, calories_per_day, protein_amount) VALUES ('Rum', 231, 2000, 0);
INSERT INTO caloric_items (item_name, calorie_count, calories_per_day, protein_amount) VALUES ('Gin', 263, 2000, 0);
INSERT INTO caloric_items (item_name, calorie_count, calories_per_day, protein_amount) VALUES ('Water', 0, 2000, 0);