INSERT INTO caloric_items (item_name, calorie_count, calories_per_day) VALUES ('Apple', 52, 2000);
INSERT INTO caloric_items (item_name, calorie_count, calories_per_day) VALUES ('Banana', 89, 2000);
INSERT INTO caloric_items (item_name, calorie_count, calories_per_day) VALUES ('Orange', 47, 2000);
INSERT INTO caloric_items (item_name, calorie_count, calories_per_day) VALUES ('Grapes', 69, 2000);
INSERT INTO caloric_items (item_name, calorie_count, calories_per_day) VALUES ('Watermelon', 30, 2000);
INSERT INTO caloric_items (item_name, calorie_count, calories_per_day) VALUES ('Mango', 60, 2000);
INSERT INTO caloric_items (item_name, calorie_count, calories_per_day) VALUES ('Strawberry', 33, 2000);
INSERT INTO caloric_items (item_name, calorie_count, calories_per_day) VALUES ('Pineapple', 50, 2000);
INSERT INTO caloric_items (item_name, calorie_count, calories_per_day) VALUES ('Papaya', 43, 2000);
INSERT INTO caloric_items (item_name, calorie_count, calories_per_day) VALUES ('Avocado', 160, 2000);
INSERT INTO caloric_items (item_name, calorie_count, calories_per_day) VALUES ('Tomato', 18, 2000);
INSERT INTO caloric_items (item_name, calorie_count, calories_per_day) VALUES ('Potato', 77, 2000);
INSERT INTO caloric_items (item_name, calorie_count, calories_per_day) VALUES ('Carrot', 41, 2000);
INSERT INTO caloric_items (item_name, calorie_count, calories_per_day) VALUES ('Broccoli', 34, 2000);
INSERT INTO caloric_items (item_name, calorie_count, calories_per_day) VALUES ('Cucumber', 16, 2000);
INSERT INTO caloric_items (item_name, calorie_count, calories_per_day) VALUES ('Spinach', 23, 2000);
INSERT INTO caloric_items (item_name, calorie_count, calories_per_day) VALUES ('Onion', 40, 2000);
INSERT INTO caloric_items (item_name, calorie_count, calories_per_day) VALUES ('Garlic', 149, 2000);
INSERT INTO caloric_items (item_name, calorie_count, calories_per_day) VALUES ('Peas', 81, 2000);
INSERT INTO caloric_items (item_name, calorie_count, calories_per_day) VALUES ('Corn', 86, 2000);
INSERT INTO caloric_items (item_name, calorie_count, calories_per_day) VALUES ('Rice', 130, 2000);
INSERT INTO caloric_items (item_name, calorie_count, calories_per_day) VALUES ('Pasta', 131, 2000);
INSERT INTO caloric_items (item_name, calorie_count, calories_per_day) VALUES ('Bread', 265, 2000);
INSERT INTO caloric_items (item_name, calorie_count, calories_per_day) VALUES ('Oatmeal', 68, 2000);
INSERT INTO caloric_items (item_name, calorie_count, calories_per_day) VALUES ('Egg', 155, 2000);
INSERT INTO caloric_items (item_name, calorie_count, calories_per_day) VALUES ('Chicken Breast', 165, 2000);
INSERT INTO caloric_items (item_name, calorie_count, calories_per_day) VALUES ('Beef', 250, 2000);
INSERT INTO caloric_items (item_name, calorie_count, calories_per_day) VALUES ('Pork', 242, 2000);
INSERT INTO caloric_items (item_name, calorie_count, calories_per_day) VALUES ('Lamb', 294, 2000);
INSERT INTO caloric_items (item_name, calorie_count, calories_per_day) VALUES ('Fish (Salmon)', 208, 2000);
INSERT INTO caloric_items (item_name, calorie_count, calories_per_day) VALUES ('Shrimp', 99, 2000);
INSERT INTO caloric_items (item_name, calorie_count, calories_per_day) VALUES ('Tuna', 132, 2000);
INSERT INTO caloric_items (item_name, calorie_count, calories_per_day) VALUES ('Milk', 42, 2000);
INSERT INTO caloric_items (item_name, calorie_count, calories_per_day) VALUES ('Cheese', 402, 2000);
INSERT INTO caloric_items (item_name, calorie_count, calories_per_day) VALUES ('Butter', 717, 2000);
INSERT INTO caloric_items (item_name, calorie_count, calories_per_day) VALUES ('Yogurt', 59, 2000);
INSERT INTO caloric_items (item_name, calorie_count, calories_per_day) VALUES ('Ice Cream', 207, 2000);
INSERT INTO caloric_items (item_name, calorie_count, calories_per_day) VALUES ('Chocolate', 546, 2000);
INSERT INTO caloric_items (item_name, calorie_count, calories_per_day) VALUES ('Coffee', 2, 2000);
INSERT INTO caloric_items (item_name, calorie_count, calories_per_day) VALUES ('Tea', 1, 2000);
INSERT INTO caloric_items (item_name, calorie_count, calories_per_day) VALUES ('Sugar', 387, 2000);
INSERT INTO caloric_items (item_name, calorie_count, calories_per_day) VALUES ('Honey', 304, 2000);
INSERT INTO caloric_items (item_name, calorie_count, calories_per_day) VALUES ('Olive Oil', 884, 2000);
INSERT INTO caloric_items (item_name, calorie_count, calories_per_day) VALUES ('Coconut Oil', 862, 2000);
INSERT INTO caloric_items (item_name, calorie_count, calories_per_day) VALUES ('Peanut Butter', 588, 2000);
INSERT INTO caloric_items (item_name, calorie_count, calories_per_day) VALUES ('Almonds', 579, 2000);
INSERT INTO caloric_items (item_name, calorie_count, calories_per_day) VALUES ('Walnuts', 654, 2000);
INSERT INTO caloric_items (item_name, calorie_count, calories_per_day) VALUES ('Cashews', 553, 2000);
INSERT INTO caloric_items (item_name, calorie_count, calories_per_day) VALUES ('Peanuts', 567, 2000);
INSERT INTO caloric_items (item_name, calorie_count, calories_per_day) VALUES ('Sunflower Seeds', 584, 2000);
INSERT INTO caloric_items (item_name, calorie_count, calories_per_day) VALUES ('Pumpkin Seeds', 559, 2000);
INSERT INTO caloric_items (item_name, calorie_count, calories_per_day) VALUES ('Lentils', 116, 2000);
INSERT INTO caloric_items (item_name, calorie_count, calories_per_day) VALUES ('Chickpeas', 164, 2000);
INSERT INTO caloric_items (item_name, calorie_count, calories_per_day) VALUES ('Kidney Beans', 127, 2000);
INSERT INTO caloric_items (item_name, calorie_count, calories_per_day) VALUES ('Tofu', 76, 2000);
INSERT INTO caloric_items (item_name, calorie_count, calories_per_day) VALUES ('Soybeans', 446, 2000);
INSERT INTO caloric_items (item_name, calorie_count, calories_per_day) VALUES ('Tempeh', 193, 2000);
INSERT INTO caloric_items (item_name, calorie_count, calories_per_day) VALUES ('Quinoa', 120, 2000);
INSERT INTO caloric_items (item_name, calorie_count, calories_per_day) VALUES ('Couscous', 112, 2000);
INSERT INTO caloric_items (item_name, calorie_count, calories_per_day) VALUES ('Barley', 354, 2000);
INSERT INTO caloric_items (item_name, calorie_count, calories_per_day) VALUES ('Buckwheat', 343, 2000);
INSERT INTO caloric_items (item_name, calorie_count, calories_per_day) VALUES ('Rye', 335, 2000);
INSERT INTO caloric_items (item_name, calorie_count, calories_per_day) VALUES ('Oats', 389, 2000);
INSERT INTO caloric_items (item_name, calorie_count, calories_per_day) VALUES ('Wheat Flour', 364, 2000);
INSERT INTO caloric_items (item_name, calorie_count, calories_per_day) VALUES ('Pancakes', 227, 2000);
INSERT INTO caloric_items (item_name, calorie_count, calories_per_day) VALUES ('Waffles', 291, 2000);
INSERT INTO caloric_items (item_name, calorie_count, calories_per_day) VALUES ('Croissant', 406, 2000);
INSERT INTO caloric_items (item_name, calorie_count, calories_per_day) VALUES ('Bagel', 250, 2000);
INSERT INTO caloric_items (item_name, calorie_count, calories_per_day) VALUES ('Burger Patty', 295, 2000);
INSERT INTO caloric_items (item_name, calorie_count, calories_per_day) VALUES ('Hotdog', 290, 2000);
INSERT INTO caloric_items (item_name, calorie_count, calories_per_day) VALUES ('Pizza', 266, 2000);
INSERT INTO caloric_items (item_name, calorie_count, calories_per_day) VALUES ('French Fries', 312, 2000);
INSERT INTO caloric_items (item_name, calorie_count, calories_per_day) VALUES ('Popcorn', 387, 2000);
INSERT INTO caloric_items (item_name, calorie_count, calories_per_day) VALUES ('Chips', 536, 2000);
INSERT INTO caloric_items (item_name, calorie_count, calories_per_day) VALUES ('Noodles', 138, 2000);
INSERT INTO caloric_items (item_name, calorie_count, calories_per_day) VALUES ('Ramen', 380, 2000);
INSERT INTO caloric_items (item_name, calorie_count, calories_per_day) VALUES ('Dumplings', 229, 2000);
INSERT INTO caloric_items (item_name, calorie_count, calories_per_day) VALUES ('Spring Roll', 154, 2000);
INSERT INTO caloric_items (item_name, calorie_count, calories_per_day) VALUES ('Sushi', 130, 2000);
INSERT INTO caloric_items (item_name, calorie_count, calories_per_day) VALUES ('Cereal', 379, 2000);
INSERT INTO caloric_items (item_name, calorie_count, calories_per_day) VALUES ('Granola', 471, 2000);
INSERT INTO caloric_items (item_name, calorie_count, calories_per_day) VALUES ('Porridge', 71, 2000);
INSERT INTO caloric_items (item_name, calorie_count, calories_per_day) VALUES ('Soup (Tomato)', 40, 2000);
INSERT INTO caloric_items (item_name, calorie_count, calories_per_day) VALUES ('Soup (Chicken)', 75, 2000);
INSERT INTO caloric_items (item_name, calorie_count, calories_per_day) VALUES ('Soup (Vegetable)', 45, 2000);
INSERT INTO caloric_items (item_name, calorie_count, calories_per_day) VALUES ('Salad (Mixed)', 33, 2000);
INSERT INTO caloric_items (item_name, calorie_count, calories_per_day) VALUES ('Caesar Salad', 190, 2000);
INSERT INTO caloric_items (item_name, calorie_count, calories_per_day) VALUES ('Taco', 226, 2000);
INSERT INTO caloric_items (item_name, calorie_count, calories_per_day) VALUES ('Burrito', 206, 2000);
INSERT INTO caloric_items (item_name, calorie_count, calories_per_day) VALUES ('Enchilada', 168, 2000);
INSERT INTO caloric_items (item_name, calorie_count, calories_per_day) VALUES ('Fajita', 201, 2000);
INSERT INTO caloric_items (item_name, calorie_count, calories_per_day) VALUES ('Lasagna', 135, 2000);
INSERT INTO caloric_items (item_name, calorie_count, calories_per_day) VALUES ('Spaghetti', 158, 2000);
INSERT INTO caloric_items (item_name, calorie_count, calories_per_day) VALUES ('Meatballs', 257, 2000);
INSERT INTO caloric_items (item_name, calorie_count, calories_per_day) VALUES ('Steak', 271, 2000);
INSERT INTO caloric_items (item_name, calorie_count, calories_per_day) VALUES ('Roast Beef', 217, 2000);
INSERT INTO caloric_items (item_name, calorie_count, calories_per_day) VALUES ('Ham', 145, 2000);
INSERT INTO caloric_items (item_name, calorie_count, calories_per_day) VALUES ('Bacon', 541, 2000);
INSERT INTO caloric_items (item_name, calorie_count, calories_per_day) VALUES ('Sausage', 301, 2000);
INSERT INTO caloric_items (item_name, calorie_count, calories_per_day) VALUES ('Turkey', 189, 2000);
INSERT INTO caloric_items (item_name, calorie_count, calories_per_day) VALUES ('Duck', 337, 2000);
INSERT INTO caloric_items (item_name, calorie_count, calories_per_day) VALUES ('Goose', 305, 2000);
INSERT INTO caloric_items (item_name, calorie_count, calories_per_day) VALUES ('Crab', 97, 2000);
INSERT INTO caloric_items (item_name, calorie_count, calories_per_day) VALUES ('Lobster', 89, 2000);
INSERT INTO caloric_items (item_name, calorie_count, calories_per_day) VALUES ('Clams', 74, 2000);
INSERT INTO caloric_items (item_name, calorie_count, calories_per_day) VALUES ('Oysters', 68, 2000);
INSERT INTO caloric_items (item_name, calorie_count, calories_per_day) VALUES ('Mussels', 86, 2000);
INSERT INTO caloric_items (item_name, calorie_count, calories_per_day) VALUES ('Scallops', 111, 2000);
INSERT INTO caloric_items (item_name, calorie_count, calories_per_day) VALUES ('Prawns', 99, 2000);
INSERT INTO caloric_items (item_name, calorie_count, calories_per_day) VALUES ('Octopus', 164, 2000);
INSERT INTO caloric_items (item_name, calorie_count, calories_per_day) VALUES ('Squid', 92, 2000);
INSERT INTO caloric_items (item_name, calorie_count, calories_per_day) VALUES ('Calamari', 175, 2000);
INSERT INTO caloric_items (item_name, calorie_count, calories_per_day) VALUES ('Anchovies', 210, 2000);
INSERT INTO caloric_items (item_name, calorie_count, calories_per_day) VALUES ('Mackerel', 205, 2000);
INSERT INTO caloric_items (item_name, calorie_count, calories_per_day) VALUES ('Trout', 141, 2000);
INSERT INTO caloric_items (item_name, calorie_count, calories_per_day) VALUES ('Sardines', 208, 2000);
INSERT INTO caloric_items (item_name, calorie_count, calories_per_day) VALUES ('Herring', 158, 2000);
INSERT INTO caloric_items (item_name, calorie_count, calories_per_day) VALUES ('Catfish', 105, 2000);
INSERT INTO caloric_items (item_name, calorie_count, calories_per_day) VALUES ('Cod', 82, 2000);
INSERT INTO caloric_items (item_name, calorie_count, calories_per_day) VALUES ('Haddock', 90, 2000);
INSERT INTO caloric_items (item_name, calorie_count, calories_per_day) VALUES ('Halibut', 140, 2000);
INSERT INTO caloric_items (item_name, calorie_count, calories_per_day) VALUES ('Tilapia', 129, 2000);
INSERT INTO caloric_items (item_name, calorie_count, calories_per_day) VALUES ('Snapper', 100, 2000);
INSERT INTO caloric_items (item_name, calorie_count, calories_per_day) VALUES ('Eggplant', 25, 2000);
INSERT INTO caloric_items (item_name, calorie_count, calories_per_day) VALUES ('Zucchini', 17, 2000);
INSERT INTO caloric_items (item_name, calorie_count, calories_per_day) VALUES ('Bell Pepper', 31, 2000);
INSERT INTO caloric_items (item_name, calorie_count, calories_per_day) VALUES ('Chili Pepper', 40, 2000);
INSERT INTO caloric_items (item_name, calorie_count, calories_per_day) VALUES ('Cabbage', 25, 2000);
INSERT INTO caloric_items (item_name, calorie_count, calories_per_day) VALUES ('Cauliflower', 25, 2000);
INSERT INTO caloric_items (item_name, calorie_count, calories_per_day) VALUES ('Kale', 49, 2000);
INSERT INTO caloric_items (item_name, calorie_count, calories_per_day) VALUES ('Lettuce', 15, 2000);
INSERT INTO caloric_items (item_name, calorie_count, calories_per_day) VALUES ('Mushroom', 22, 2000);
INSERT INTO caloric_items (item_name, calorie_count, calories_per_day) VALUES ('Celery', 16, 2000);
INSERT INTO caloric_items (item_name, calorie_count, calories_per_day) VALUES ('Radish', 16, 2000);
INSERT INTO caloric_items (item_name, calorie_count, calories_per_day) VALUES ('Beetroot', 43, 2000);
INSERT INTO caloric_items (item_name, calorie_count, calories_per_day) VALUES ('Turnip', 28, 2000);
INSERT INTO caloric_items (item_name, calorie_count, calories_per_day) VALUES ('Sweet Potato', 86, 2000);
INSERT INTO caloric_items (item_name, calorie_count, calories_per_day) VALUES ('Pumpkin', 26, 2000);
INSERT INTO caloric_items (item_name, calorie_count, calories_per_day) VALUES ('Apple Pie', 237, 2000);
INSERT INTO caloric_items (item_name, calorie_count, calories_per_day) VALUES ('Donut', 452, 2000);
INSERT INTO caloric_items (item_name, calorie_count, calories_per_day) VALUES ('Cupcake', 305, 2000);
INSERT INTO caloric_items (item_name, calorie_count, calories_per_day) VALUES ('Muffin', 377, 2000);
INSERT INTO caloric_items (item_name, calorie_count, calories_per_day) VALUES ('Brownie', 405, 2000);
INSERT INTO caloric_items (item_name, calorie_count, calories_per_day) VALUES ('Pancake Syrup', 260, 2000);
INSERT INTO caloric_items (item_name, calorie_count, calories_per_day) VALUES ('Jam', 278, 2000);
INSERT INTO caloric_items (item_name, calorie_count, calories_per_day) VALUES ('Ketchup', 112, 2000);
INSERT INTO caloric_items (item_name, calorie_count, calories_per_day) VALUES ('Mayonnaise', 680, 2000);
INSERT INTO caloric_items (item_name, calorie_count, calories_per_day) VALUES ('Mustard', 66, 2000);
INSERT INTO caloric_items (item_name, calorie_count, calories_per_day) VALUES ('Vinegar', 21, 2000);
INSERT INTO caloric_items (item_name, calorie_count, calories_per_day) VALUES ('Soy Sauce', 53, 2000);
INSERT INTO caloric_items (item_name, calorie_count, calories_per_day) VALUES ('BBQ Sauce', 175, 2000);
INSERT INTO caloric_items (item_name, calorie_count, calories_per_day) VALUES ('Hot Sauce', 12, 2000);
INSERT INTO caloric_items (item_name, calorie_count, calories_per_day) VALUES ('Salad Dressing', 430, 2000);
INSERT INTO caloric_items (item_name, calorie_count, calories_per_day) VALUES ('Ice Tea', 30, 2000);
INSERT INTO caloric_items (item_name, calorie_count, calories_per_day) VALUES ('Lemonade', 40, 2000);
INSERT INTO caloric_items (item_name, calorie_count, calories_per_day) VALUES ('Coke', 42, 2000);
INSERT INTO caloric_items (item_name, calorie_count, calories_per_day) VALUES ('Sprite', 41, 2000);
INSERT INTO caloric_items (item_name, calorie_count, calories_per_day) VALUES ('Orange Juice', 45, 2000);
INSERT INTO caloric_items (item_name, calorie_count, calories_per_day) VALUES ('Apple Juice', 46, 2000);
INSERT INTO caloric_items (item_name, calorie_count, calories_per_day) VALUES ('Grape Juice', 60, 2000);
INSERT INTO caloric_items (item_name, calorie_count, calories_per_day) VALUES ('Milkshake', 112, 2000);
INSERT INTO caloric_items (item_name, calorie_count, calories_per_day) VALUES ('Smoothie', 50, 2000);
INSERT INTO caloric_items (item_name, calorie_count, calories_per_day) VALUES ('Beer', 43, 2000);
INSERT INTO caloric_items (item_name, calorie_count, calories_per_day) VALUES ('Wine', 85, 2000);
INSERT INTO caloric_items (item_name, calorie_count, calories_per_day) VALUES ('Whiskey', 250, 2000);
INSERT INTO caloric_items (item_name, calorie_count, calories_per_day) VALUES ('Vodka', 231, 2000);
INSERT INTO caloric_items (item_name, calorie_count, calories_per_day) VALUES ('Rum', 231, 2000);
INSERT INTO caloric_items (item_name, calorie_count, calories_per_day) VALUES ('Gin', 263, 2000);
INSERT INTO caloric_items (item_name, calorie_count, calories_per_day) VALUES ('Water', 0, 2000);
